/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/db2e1926-0acf-4e15-917b-1c670657e8db 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool lightTrigger;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
int sec=0;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(13,OUTPUT);
  digitalWrite(13,HIGH);
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  sec+=1;
  if(sec==60){
      lightTrigger=true;
      Serial.println("its working");
      justIntValue=60;
  }

  delay(1000);
  
}

/*
  Since LightTrigger is READ_WRITE variable, onLightTriggerChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLightTriggerChange()  {
  // Add your code here to act upon LightTrigger change
  if(lightTrigger){
    digitalWrite(13,LOW);
    delay(3000);
    digitalWrite(13,HIGH);
    lightTrigger=false;
  }
  else{
    digitalWrite(13,HIGH);
  }
  
}
void onJustIntValueChange(){
    Serial.println(justIntValue);
}