// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "6cfc6d58-f0e3-4c01-92cd-9175f93c6bb8";

const char SSID[]               = "fbi_open";    // Network SSID (name)
const char PASS[]               = "qwertyxiop";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "OP6A5BB5G8QTJSFNYRWE";    // Secret device password

void onLightTriggerChange();
void onJustIntValueChange();

bool lightTrigger;
int justIntValue;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(lightTrigger, READWRITE, ON_CHANGE, onLightTriggerChange);
  ArduinoCloud.addProperty(justIntValue,READWRITE,ON_CHANGE,onJustIntValueChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
